environment:
  matrix:
  - nodejs_version: "4.2"
  - nodejs_version: "5.5"
  - nodejs_version: "6.3"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm install -g grunt-cli

test_script:
  - node --version
  - npm --version
  - grunt --version
  - grunt

build: off
